/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Boost Point gain based on Incremental Points": "提升点数增益基于增量点",
    "Double your point gain.": "双倍你的点数增益。",
    "Incremental Game?": "增量游戏？",
    "incremental points": " 增量点",
    "It's a Great Idea": "这是个好主意",
    "The Beginning of the Idea": "想法的开始",
    "Triple your point gain.": "三倍你的点数增益。",
    "Boost Point gain based on Points": "提升点数增益基于点数",
    "Or Maybe Idle Game": "或者也许是放置游戏",
    "Boost Incremental Points based on Incremental Points": "提升增量点增益基于增量点",
    "I should start making the game?": "我应该开始制作游戏吗？",
    "Learn Coding": "学习编码",
    "Passively Generate Cookies": "被动生成饼干",
    "Start making the game": "开始制作游戏",
    "Upgrades": "升级",
    "You are gaining NaN incremental points per second": "您每秒获得 NaN 增量点",
    "Autobuys all the upgrades": "自动购买所有升级",
    "Autobuys the first 4 buyables and it does not deduct your Incremental Points": "自动购买前 4 个可购买，并且不会扣除您的增量点",
    "Automated Coding Lessons": "自动编码课程",
    "Clicker": "点击器",
    "Cookies": "饼干",
    "Free Points": "免费点数",
    "Gather Ideas": "收集想法",
    "Get 1e14 Incremental Points per second and autobuys the rest of the buyables": "每秒获得 1e14 增量点 并自动购买剩余的可购买",
    "Gain 100% of Incremental Points per second, and unlocks cool stuff": "每秒获得 100% 的增量点，并解锁很酷的东西",
    "Automates the second row of buyables": "自动化 第2行 可购买",
    "Boosts Incremental Points Based On Points": "提升增量点增益基于点数",
    "Make Developing Faster": "让开发更快",
    "Passive Income": "被动收入",
    "Pure Automation": "纯自动化",
    "Resets Sound Like a good idea!": "重置听起来是个好主意！",
    "Unlocks more cool stuff": "解锁更多酷的东西",
    "Prestige Function": "声望功能",
    "Time for rest can help right?": "休息时间可以帮助吗？",
    "Boost to Points and Incremental Points based on Time Played": "根据游戏时间提升点数和增量点",
    "Finish Coding": "完成编码",
    "Buying Prestige Functions doesnt reset anything": "购买声望功能不会重置任何东西",
    "Make the game look good": "让游戏看起来不错",
    "Non Resetting Layers": "非重置层",
    "Test The Game": "测试游戏",
    "Publish the Game": "发布游戏",
    "Unlocks a new layer (Finally": "解锁新层（最后",
    "Cookie Clicker": "饼干点击器",
    "Cursor": "游标",
    "A Revolutionary Idea": "一个革命性的想法",
    "Add a Timewall": "添加时间墙",
    "Adds ^46 to the Cookie Time Effect": "将 ^46 添加到 饼干 时间效果",
    "Advertise Your Patreon": "宣传你的 Patreon",
    "Apartment": "公寓",
    "Ascended Heavenly Chip Shoes": "升天筹码鞋",
    "Automates buying Dimensional Grandmas and Dimensional Wrinklers": "自动购买 维度老奶奶 和 维度皱纹",
    "Automatic Timewalls": "自动时间墙",
    "Automatically buys Church Buyables": "自动购买教堂可购买物品",
    "Automatically gets Timewalls": "自动获取时间墙",
    "Automatically sends 10% of your $ to your savings account without losing any of your $": "自动将 10% 的美元存入您的储蓄账户，而不会损失任何美元",
    "Automatically Walks 10 Meters Per Second": "每秒自动行走 10 米",
    "Autowalks Forward Faster based on Sugar Lumps": "基于 糖块 更快地自动行走",
    "Autowalks Right Faster based on Heavenly Chips": "基于 天堂筹码 的自动行走更快",
    "Big Mac": "巨无霸",
    "Blood Donation": "献血",
    "Boost all Dimensional Cookie gain by 10 and unlocks a new tab": "将所有 维度饼干 增益提高 10 并解锁新标签",
    "Boost Cultists based on Cultists": "基于邪教徒提升邪教徒",
    "Boosts $ based on $": "基于 $ 提升 $",
    "Boosts $ based on Research Points": "根据研究点增加 $",
    "Boosts Antimatter based on $": "基于 $ 提升反物质",
    "Boosts autobuyer.js based on $": "基于 $ 提升 autobuyer.js",
    "Boosts autobuyer.js based on Research Points": "基于研究点提升 autobuyer.js",
    "Boosts Autowalking Speed based on time played": "根据播放时间提高自动行走速度",
    "Boosts breakinfinity.js based on $": "基于 $ 提升 breakinfinity.js",
    "Boosts breakinfinity.js based on Research Points": "基于研究点提升 breakinfinity.js",
    "Boosts Cookie Bibles based on $": "基于 $ 提升 饼干 圣经",
    "Boosts Cookie Blood based on $": "基于 $ 提升 饼干之血",
    "Boosts Cookie Blood Gain based on Cookie Bibles": "根据饼干圣经提高饼干血量",
    "Boosts Cookie Blood Gain based on Cultists": "增加基于邪教徒的饼干血量",
    "Boosts Cookie Time based on Research Points": "根据研究点增加 饼干 时间",
    "Boosts Cookies based on $": "基于 $ 提升 饼干",
    "Boosts Cookies based on Cookie Ascensions, and start producing dimensional cookies": "基于 饼干转生 提升 饼干，并开始制作立体 饼干",
    "Boosts Cookies Based on Patreon Subscribers": "提升基于 Patreon 订阅者的 饼干",
    "Boosts Cookies based on Research Points": "根据研究点提升 饼干",
    "Boosts Cultists based on $": "基于 $ 提升邪教徒",
    "Boosts Dimensional Cookies based on Research Points": "根据研究点提升立体饼干",
    "Boosts Dimensional Sugar Lumps based on Research Points": "根据研究点提升立体糖块",
    "Boosts game.js based on $": "基于 $ 提升 game.js",
    "Boosts game.js based on Research Points": "基于研究点提升 game.js",
    "Boosts Heavenly Chips based on Research Points": "根据研究点提升天堂筹码",
    "Boosts Heavenly Chips based on Y Cookies": "基于 Y 饼干 提升天堂筹码",
    "Boosts Hevipelle Points based on $": "基于 $ 提升 hevipelle 点数",
    "Boosts Incremental Points based on $": "增加基于 $ 的增量点",
    "Boosts Incremental Points based on Research Points": "根据研究点增加增量点",
    "Boosts Patreon Subscribers based on $": "基于 $ 提升 Patreon 订阅者",
    "Boosts Patreon Subscribers based on Research Points": "根据研究点增加 Patreon 订阅者",
    "Boosts Points based on $": "根据 $ 提升点数",
    "Boosts Points based on Research Points": "根据研究点提升点",
    "Boosts Research Points based on $": "基于 $ 提升研究点数",
    "Boosts Sugar Lumps based on Research Points": "根据研究点增加糖块",
    "Boosts Sugar Lumps based on X Cookies": "基于 X 饼干 增加糖块",
    "Boosts X and Y Cookies based on Z Cookies": "基于 Z 饼干 提升 X 和 Y 饼干",
    "Boosts X Cookies based on X Cookie Grandmas": "基于 X 饼干老奶奶 提升 X 饼干",
    "Boosts X Cookies based on X Sugar Lumps": "基于 X 糖块 提升 X 饼干",
    "Boosts Y Cookies based on Y Cookie Grandmas": "基于 Y 饼干老奶奶 提升 Y 饼干",
    "Boosts Y Cookies based on Y Sugar Lumps": "基于 Y 糖块提升 Y 饼干",
    "Boosts Z Cookies based on Z Cookie Grandmas": "基于 Z 饼干老奶奶 提升 Z 饼干",
    "Boosts Z Cookies based on Z Sugar Lumps": "基于 Z 糖块提升 Z 饼干",
    "Break the laws of Cookie Physics": "打破饼干物理定律",
    "Cheap TV": "廉价电视",
    "Chromebook": "铬本",
    "Cookie Church": "饼干教堂",
    "Unlocks the Church": "解锁教堂",
    "Walk Forward": "向前走",
    "Walk Right": "向右走",
    "Week Long Vacation": "一周长假",
    "which multiplies Research Point and Cookie Time gain by x22,937": "将研究点数和 饼干 时间增益乘以 x22,937",
    "X cookie booster": "X 饼干助推器",
    "X Cookie Grandma": "X 饼干老奶奶",
    "X cookie synergy": "X 饼干协同作用",
    "X Cookie Wrinkler": "X 饼干皱纹机",
    "X Sugar Lumps are gained based on how much you traveled right, Y Sugar Lumps are gained based on how much you traveled forward, Z Sugar Lumps are gained based on both positions": "X 糖块是根据您正确行驶的距离获得的，Y 糖块是根据您前进的距离获得的，Z 糖块是根据两个位置获得的",
    "X sugar lumps booster": "X 糖块助推器",
    "Y cookie booster": "Y饼干助推器",
    "Y Cookie Grandma": "Y饼干奶奶",
    "Y cookie synergy": "Y 饼干协同作用",
    "Y Cookie Wrinkler": "Y 饼干皱纹机",
    "Y sugar lumps booster": "Y糖块助推器",
    "You Gain Dollars Based on the Log10(Log10)^0.5/250 of Points you have": "您根据您拥有的点数的 Log10(Log10)^0.5/250 获得 $",
    "Start Creating for autobuyer.js": "开始创建 autobuyer.js",
    "Start Creating for breakinfinity.js": "开始创建 breakinfinity.js",
    "Start Creating for game.js": "开始创建 game.js",
    "Timewalls": "时间墙",
    "Timewalls?": "时间墙？",
    "Unlock Timewalls": "解锁时间墙",
    "Life": "生活",
    "Multiplies Cookie Clicker Time gain by 1000x": "将 饼干点击器 时间增益乘以 1000 倍",
    "Polynomial Growth?": "多项式增长？",
    "Different from Cookie Clicker": "不同于 饼干点击器",
    "Game Development": "游戏开发",
    "Gives you Lines of Code for autobuyer.js based on Hevipelle Points": "为您提供基于 hevipelle 点数的 autobuyer.js 代码行",
    "Gives you Lines of Code for breakinfinity.js based on Hevipelle Points": "为您提供基于 hevipelle 点的 breakinfinity.js 代码行",
    "Gives you Lines of Code for game.js based on Hevipelle Points": "为您提供基于 hevipelle 点数的 game.js 代码行",
    "hevipelle points": "hevipelle点",
    "Antimatter Dimensions": "反物质维度",
    "Hevi Timewalls": "赫维时间墙",
    "Speed up the Timewalls": "加速时间墙",
    "Speeds up Timewall Seconds gain by 3x and Automatically generate Hevipelle points": "将 时间墙 秒数提高 3 倍并自动生成 hevipelle点数",
    "Timewalls boost Hevipelle points": "时间墙提升 hevipelle点数",
    "Unlocks a new Tab": "解锁新标签页",
    "Z cookie booster": "Z 饼干助推器",
    "Z Cookie Grandma": "Z 饼干奶奶",
    "Z cookie synergy": "Z 饼干协同作用",
    "Z Cookie Wrinkler": "Z 饼干起皱机",
    "The Final Cookie": "最后的饼干",
    "The New Testament": "新约",
    "Train your mind to make you automatically run": "训练你的头脑，让你自动奔跑",
    "Unlock the third quarter of this layer": "解锁本层的第三部分",
    "Exploration": "探索",
    "Extended Cookie Clicker": "扩展的饼干点击器",
    "Heralds": "使者",
    "Look for Dimensional Sugar Lumps?": "寻找维度糖块？",
    "Money is Power": "金钱就是力量",
    "Patreon (SUS": "Patreon (SUS",
    "Sorry no more cool function OmegaNum is STUPID and doesnt allow negatives! NOT COOL OMEGANUM": "抱歉，没有更酷的功能 OmegaNum 是愚蠢的，不允许否定！ 不酷的OMEGANUM",
    "Sugar Lump flavored Gatorade": "糖块味的佳得乐",
    "The Big Boost": "大提升",
    "Z sugar lumps booster": "Z 糖块助推器",
    "Cookie Ritual Activation": "饼干仪式激活",
    "Cookie Ritual Deactivation": "饼干仪式停用",
    "Cookie Trollge": "饼干小精灵",
    "Priest Grandma": "牧师老奶奶",
    "Revelation": "启示",
    "Sacrifice Cultists": "牺牲邪教徒",
    "SUMMON THE COOKIE GOD OF GODS": "召唤众神的饼干之神",
    "2000 Server Boosts to the Cookie Clicker discord server": "2000 服务器提升到 饼干点击器 discord服务器",
    "Research game.js Boost": "研究game.js 提升",
    "Research Heavenly Chips Boost": "研究天堂筹码助推器",
    "Research Incremental Point Boost": "研究增量点提升",
    "Research Patreon Boost": "研究 Patreon 提升",
    "Research Point Boost": "研究点提升",
    "Research Sugar Lumps Point Boost": "研究糖块点提升",
    "Research Tree": "研究树",
    "Router": "路由器",
    "Speed things up a bit": "加快速度",
    "Supermarket": "超级市场",
    "The List of Games Made": "制作的游戏列表",
    "Unlocks a new layer": "解锁新图层",
    "Unlocks a new tab": "解锁新标签",
    "Unlocks a new tab in the Cookie Clicker layer": "解锁 饼干点击器 层中的新选项卡",
    "Deposit Money into Savings Account": "将钱存入储蓄账户",
    "Finance": "金融",
    "Gaming PC": "游戏电脑",
    "Get Ready for another layer...": "准备好下一层...",
    "Gold Bar": "金条",
    "Grand Piano": "三角钢琴",
    "Headphones": "耳机",
    "Make another Game": "制作另一个游戏",
    "Notebook": "笔记本",
    "Oven": "烤箱",
    "Research $ Boost": "研究 $ 提升",
    "Research autobuyer.js Boost": "研究 autobuyer.js 提升",
    "Research breakinfinity.js Boost": "研究breakinfinity.js 提升",
    "Research Cookie Boost": "研究饼干提升",
    "Research Dimensional Cookies Boost": "研究 维度饼干 提升",
    "Research Dimensional Sugar Lumps Boost": "研究 维度糖块 提升",
    "1st Dimension": "第 1 维度",
    "JOIN THE WAR NOW!! COME ON SOLDIER WE NEED YOU!!": "现在加入战争！来吧士兵我们需要你！",
    "Make Respect have a new Purpose that is better than the last one": "让尊重有一个比上一个更好的新目的",
    "Makes Item gain 2 times faster": "使物品获得速度加快 2 倍",
    "Makes Training 2x Faster, as well as getting 2x the Respect.": "使培训速度提高 2 倍，并获得 2 倍的尊重。",
    "Military": "军队",
    "MRE Meals": "MRE 膳食",
    "New Opportunities": "新的机会",
    "No more Constant Switching": "不再持续切换",
    "Point-Cookie Synergy": "点饼干协同作用",
    "Points and Cookies-Incremental Point Synergy": "点数和饼干-增量点数协同",
    "Points boost Cookie gain": "点数提升 饼干 增益",
    "Points boost Sugar Lumps Gain": "点数提高糖块增益",
    "Points-Sugar Lumps Synergy": "点-糖块协同作用",
    "Produce Gain Shards and Effect Shards at the Same time": "同时产生增益碎片和效果碎片",
    "Replicanti": "复制品",
    "Sell your Items": "出售您的物品",
    "Speed Shipping": "快速发货",
    "Start producing Effect Shards": "开始制作效果碎片",
    "Start producing Gain Shards": "开始生产增益碎片",
    "Start producing Hevipelle Shards": "开始生产 Hevipelle 碎片",
    "START THE GRANDMAPOCALYPSE": "开始大启示录",
    "Start Training": "开始训练",
    "Subatomic Particles": "亚原子粒子",
    "Sugar Lumps boost Cookie gain": "糖块提高饼干增益",
    "Sugar Lumps boost Incremental Point gain": "糖块提高增量点增益",
    "Sugar Lumps boost Point gain": "糖块提高点数增益",
    "Sugar Lumps boost Sugar Lumps Gain": "糖块提高糖块增益",
    "Sugar Lumps-Cookie Synergy": "糖块饼干协同作用",
    "Sugar Lumps-Incremental Point Synergy": "糖块-增量点协同",
    "Sugar Lumps-Point Synergy": "糖块点协同作用",
    "Sugar Lumps-Sugar Lumps Synergy": "糖块-糖块协同作用",
    "Supermarket Management": "超市管理",
    "The Cost of this Upgrade is Funny Number": "这次升级的成本是有趣的数字",
    "The End": "结束",
    "The End is Near...": "快到终点了...",
    "The Grandmas are Mad...": "老奶奶们疯了……",
    "THIS UPGRADE HAS NO OFF BUTTON. BE WARNED. SLOWS COOKIE GAIN BY 100 AND INCREASES SUGAR LUMP GAIN BY 10. IT IS UNCERTAIN ABOUT WHAT IS GOING TO HAPPEN NEXT.": "此升级没有关闭按钮。被警告。将 饼干 增益减慢 100 并将糖块增益增加 10。不确定接下来会发生什么。",
    "Time to get an Item": "是时候拿到物品了",
    "Training": "训练",
    "Universes": "宇宙",
    "Unlock Final Shards but turn off the other Autobuyers (For Performance": "解锁最终碎片但关闭其他自动购买者（为了性能",
    "UNLOCK THE POWER OF INCREMENTAL": "解锁增量的力量",
    "Unlock the second quarter of this layer (COOL": "解锁本层第二季（酷",
    "Unlocks more types of Shards": "解锁更多类型的碎片",
    "War": "战争",
    "WAR HAS STARTED": "战争已经开始",
    "Workaholic": "工作狂",
    "Workers": "工人",
    "Endurance Upgrade": "耐力升级",
    "Even more Inflated boosting": "更加膨胀的助推器",
    "Every time you finish your training, you get inspiration, which boosts Respect gain.": "每次完成训练时，您都会获得灵感，从而提高尊重度。",
    "Extra Demand": "额外需求",
    "Finish the Layer": "完成图层",
    "Heavenly Chip-Cookies Synergy": "天堂筹码-饼干 协同效应",
    "Heavenly Chip-Incremental Points Synergy": "天堂筹码-增量点数协同",
    "Heavenly Chip-Points and Incremental Points Synergy": "天筹点数和增量点数协同",
    "Heavenly Chip-Points Synergy": "天筹点协同",
    "Heavenly Chip-Sugar Lumps Synergy": "天堂筹码-糖块协同",
    "Hevipelle is proud...": "hevipelle很自豪...",
    "Hevipelle knows your the Chosen one": "Hevipelle 知道你的天选之人",
    "Hevipelle must be proud": "hevipelle一定很自豪",
    "Incremental Point-Cookie Synergy": "增量点-饼干 协同作用",
    "Incremental Points and Cookies-Point Synergy": "增量点数和 饼干点数 协同",
    "Incremental Points boost Cookie gain": "增量点可提高 饼干 增益",
    "Incremental Points boost Sugar Lumps Gain": "增量点提高糖块增益",
    "Extra Demand": "额外需求",
    "Gotta Keep the Game's Effects Useful": "必须保持游戏的效果有用",
    "I can't buy the Universe (Sad": "我买不到宇宙（悲伤",
    "JOIN THE MILITARY": "加入军队",
    "JOINS THE MILITARY. THERE IS NO COMING BACK.": "加入军队。没有回来。",
    "Make Respect have a new Purpose": "让尊重有一个新的目的",
    "Make Respect have a new Purpose that is better than the last one": "让尊重有一个比上一个更好的新目的",
    "Make the Effect as even better as it possibly get": "使效果尽可能好",
    "Make the Effect as good as it possibly get": "使效果尽可能好",
    "Makes Item gain 2 times faster": "使物品获得速度加快 2 倍",
    "Military": "军队",
    "New Opportunities": "新的机会",
    "Research Antimatter Boost": "研究反物质助推器",
    "Inremental Points-Sugar Lumps Synergy": "增量点-糖块 协同",
    "Inspiration": "灵感",
    "Effect Shards and Gain Shards boost each other": "效果碎片和增益碎片相互促进",
    "Effect Shards and Gain Shards boost each other even more": "效果碎片和增益碎片更加相互促进",
    "A Pretty Inflated Upgrade": "一个相当膨胀的升级",
    "Adds ^140 to the Cookie time Effect": "将 ^140 添加到 饼干 时间效果",
    "Adrenaline": "肾上腺素",
    "Advertisements": "广告",
    "All These Effects Kinda Getting Useless Again": "所有这些效果有点再次变得无用",
    "Automatically Sells when you get 100 items": "当您获得 100 件商品时自动出售",
    "Boosts Antimatter based on Research Points": "根据研究点提升反物质",
    "Boosts Antimatter Dimensions Time based on Respect": "基于尊重提高反物质维度时​​间",
    "Boosts Coins based on Respect": "基于尊重提升硬币",
    "Boosts Electrons based on Research Points": "根据研究点提升电子",
    "Boosts Hevipelle Points based on Research Points": "根据研究点数提升 Hevipelle 点数",
    "Boosts Infinity Dimensions based on Research Points": "根据研究点提升无限维度",
    "Boosts Infinity Points based on Research Points": "根据研究点提升无限点",
    "Boosts Neutrons based on Research Points": "根据研究点提升中子",
    "Boosts Protons based on Research Points": "根据研究点提升质子",
    "Boosts The Respect and Euro pow based on Euros": "提升基于欧元的尊重和欧元战俘",
    "Boosts The Respect pow based on Euros": "提升基于欧元的尊重战俘",
    "Boosts Time to make an Item based on Items you don't have": "加快根据您没有的物品制作物品的时间",
    "Boosts Time to make an Item based on Items you have": "根据您拥有的物品加快制作物品的时间",
    "Bumps Euros effect to ^150000": "将欧元效应提高到 ^150000",
    "Bumps Respect Effect to ^100 and Euros effect to ^10000": "将尊重效果提升至 ^100，将欧元效果提升至 ^10000",
    "Bumps Respect Effect to ^5": "将尊重效果提高到 ^5",
    "BUY THE SUPERMARKET": "购买超市",
    "Research Electron Boost": "研究电子助推器",
    "Research Hevipelle Boost": "研究 Hevipelle 提升",
    "Research Infinity Dimensions Boost": "研究无限维度提升",
    "Research Infinity Points Boost": "研究无限点提升",
    "Research Neutron Boost": "研究中子助推器",
    "Research Proton Boost": "研究质子助推器",
    "The Effect's Kinda Getting Useless": "效果有点没用",
    "Unlocks Supermarket Management, and Boosts Antimatter Dimensions Time by 10": "解锁超市管理，将反物质维度时​​间提高 10 倍",
    "x3 Coins gained on Sell": "x3 出售获得的金币",
    "x3 Coins gained on Sell (Again": "出售获得的 x3 硬币（再次",
    "You got so much money the value of the dollar dropped so low that you now have to use Euros": "你有这么多钱，美元贬值这么低，你现在不得不使用欧元",
    "Ends the Battle": "结束战斗",
    "Grandma": "奶奶",
    "Growing Soldier Badge: x1.2 Respect Boost (Get 50 Inspiration": "成长中的士兵徽章：x1.2 尊重提升（获得 50 点灵感",
    "If your game freezes while joining battle, just refresh your game and it is all good.": "如果您的游戏在加入战斗时卡住了，只需刷新您的游戏就可以了。",
    "Intermediate Soldier Badge: x2 Inspiration Gain (Get 60 Military Power": "中级士兵徽章：x2 灵感增益（获得 60 军事力量",
    "New Trainee Badge: x1.3 Respect Boost (Get 10 Inspiration": "新实习生徽章：x1.3 尊重提升（获得 10 点灵感",
    "RETREAT": "撤退",
    "Rookie Badge: x1.2 Respect Boost and x1.2 Training Speed and a -1 Second Cooldown Time (Get Endurance level 20": "新秀徽章：x1.2 尊重提升和 x1.2 训练速度和 -1 秒冷却时间（获得耐力等级 20",
    "START THE BATTLE": "开始战斗",
    "Starts the Battle": "开始战斗",
    "Wrinkler": "皱纹机",
    "Battle Soldier Badge: -1 Second Cooldown Time (Join the War": "战斗士兵徽章：-1 秒冷却时间（加入战争",
    "Bloodshed Badge: x1.3 Respect Boost and x1.3 Training Speed (Get 25 Military Power": "流血徽章：x1.3 尊重提升和 x1.3 训练速度（获得 25 军事力量",
    "Boost Cookie Gain based on Time Played": "根据游戏时长提高 饼干 增益",
    "Boosts Cookies based on Heavenly Chips": "提升基于天堂筹码的饼干",
    "Boosts Heavenly Chips and Sugar Lumps based on amount of Cursors": "根据游标的数量增加天堂薯片和糖块",
    "Boosts Heavenly Chips and Sugar Lumps based on amount of Grandmas": "根据祖母的数量增加天堂薯片和糖块",
    "Boosts Heavenly Chips and Sugar Lumps based on time played": "根据播放时间增加天堂筹码和糖块",
    "Boosts Incremental Points based on Heavenly Chips": "增加基于天堂筹码的增量点",
    "Boosts Incremental Points based on Points and Cookies": "根据点数和 饼干 增加增量点数",
    "Boosts Points and Incremental Points based on Heavenly Chips": "基于天筹的提升点数和增量点数",
    "Boosts Points based on amount of Grandmas": "根据祖母的数量增加点数",
    "Boosts Points based on Heavenly Chips": "提升基于天堂筹码的点数",
    "Boosts Points based on Incremental Points and Cookies": "根据增量点数和 饼干 提升点数",
    "Boosts Sugar Lumps based on Heavenly Chips": "基于天堂筹码提升糖块",
    "Boosts Wrinkler Juice based on time played": "根据播放时间提升 皱纹果汁",
    "Cookie Alchemy Lab": "饼干炼金术实验室",
    "Cookie Antimatter Condenser": "饼干反物质冷凝器",
    "Cookie Ascension": "饼干转生",
    "Cookie Bank": "饼干银行",
    "Cookie Chancemaker": "饼干改变者",
    "Cookie Devil": "饼干恶魔",
    "Cookie Engineer": "饼干工程师",
    "Cookie Factory": "饼干厂",
    "Cookie Farm": "饼干农场",
    "Cookie God": "饼干之神",
    "Cookie Goku": "饼干悟空",
    "Cookie Holy Lords": "饼干圣主",
    "Cookie Idleverse": "饼干空闲",
    "Cookie Immortality": "饼干不朽",
    "Cookie Javascript Console": "饼干 Javascript 控制台",
    "Cookie Jesus": "饼干耶稣",
    "Cookie Lord": "饼干领主",
    "Cookie Master": "饼干大师",
    "Cookie Mine": "饼干矿山",
    "Cookie Portal": "饼干传送门",
    "Cookie Prism": "饼干棱镜",
    "Cookie Rick Astley": "饼干里克·阿斯特利",
    "Cookie Shipment": "饼干装船",
    "Cookie Temple": "饼干神庙",
    "Cookie Time Machine": "饼干时光机",
    "Cookie Wizard Tower": "饼干巫师塔",
    "Cookie-Cookie Synergy": "饼干饼干协同作用",
    "Cookie-Point Synergy": "饼干点协同作用",
    "Cookies also boost Point gain": "饼干也提高了点数增益",
    "Cookies boost Cookie gain": "饼干提高饼干增益",
    "Cookies boost Sugar Lumps Gain": "饼干提高糖块增益",
    "Cookies-Sugar Lumps Synergy": "饼干-糖块协同作用",
    "Badges": "徽章",
    "You can't do training during battle": "你不能在战斗中进行训练",
    " Heroic Points": " 英雄点数",
    " Respect": " 尊重",
    "2nd Dimension": "第 2 维度",
    "3rd Dimension": "第 3 维度",
    "Even more Hevi Timewalls": "更多 赫维 时间墙",
    "Gets 2x Replicanti instead of 1.1x": "获得 2x 复制品 而不是 1.1x",
    "Gets 5x Replicanti now": "现在获得 5x 复制品",
    "Make the Timewalls Sped Up": "加速时间墙",
    "Mini Dimensions": "迷你尺寸",
    "More Singularities?": "更多奇点？",
    "Production Booster": "生产助推器",
    "Replicanti Boosts Infinity Points": "复制品 提升无限点数",
    "Replicanti Time Booster": "复制品 时间助推器",
    "Replication is now Duplication": "复制现在是复制",
    "Supreme Timewall Speed": "至高无上的时间墙速度",
    "This was never in the real game!": "这在真正的游戏中是从来没有的！",
    "Timewalls boost Timewall Effect": "时间墙提升时间墙效果",
    "We need more Infinity Points": "我们需要更多的无限点",
    "Adds a ^10 to the Cookie Time Effect and make stuff look cool (makes the node look gay?": "为 Cookie 时间效果添加 ^10 并使东西看起来很酷（使节点看起来很同性恋？",
    "Amount of Existence Converted to Antimatter": "转化为反物质的存在量",
    "Antimatter Galaxy": "反物质星系",
    "Atoms": "原子",
    "Autobuys Final 2 Rows of Cookie Buyables, and Cookie Ascensions do not reset everything and automates Cookie Ascensions.": "自动购买最后两行饼干可购买 和 饼干转生 不会重置所有内容并自动执行 饼干转生。",
    "Automates buying Dimensions and buying them doesn't deduct any Antimatter": "自动购买维度并购买它们不会扣除任何反物质",
    "Automates the Fifth row of buyables": "自动化第五排可购买",
    "Automates the First row of buyables": "自动化第一行可购买",
    "Automates the Second row of buyables": "自动化第二排可购买",
    "Automates the Third row of buyables": "自动化第三排可购买",
    "Automation, Already??? And where is the Tickspeed Boost???": "自动化，已经？？？ Tick速度提升 在哪里？？？",
    "Black Holes": "黑洞",
    "Boosts and Galaxies": "助推器和星系",
    "Boosts Electron effect Pow to ^2000": "将电子效应力量 提升至 ^2000",
    "Boosts Singularities based on Replicanti": "基于 复制品 提升奇点",
    "Breakreplicantinfinity": "断裂复制无限",
    "Completes the Layer (FINALLY": "完成图层（最后",
    "Couldn't get enought replicanti?": "无法获得足够的复制品？",
    "Dimension Boost": "维度提升",
    "Dimensional Sacrifice": "维度牺牲",
    "... Again": "... 再次",
    "1st Omega Dimension": "第 1 欧米伽维度",
    "2nd Omega Dimension": "第 2 欧米伽维度",
    "3rd Omega Dimension": "第 3 欧米伽维度",
    "1st Subatomic Dimension": "第 1 亚原子维度",
    "2nd Subatomic Dimension": "第 2 亚原子维度",
    "3rd Subatomic Dimension": "第 3 亚原子维度",
    "Double Quantum Fluctuations": "双量子涨落",
    "Doubler Automation": "倍增自动化",
    "ee2.108e16 per Second": "ee2.108e16 每秒",
    "Electric Boogaloo": "电动布加洛",
    "Even more Automation": "更加自动化",
    "Gains 100 Replicanti Boosters per Second": "每秒获得 100 个 复制品 助推器",
    "Generates Black Holes based on Infinity Points": "根据无穷大点生成黑洞",
    "Make the Dimensions useful again": "让维度再次有用",
    "Omega > Infinity": "欧米茄 > 无限",
    "Quantum Fluctuations": "量子涨落",
    "Replicanti Booster": "复制品助推器",
    "Singularity Doubler": "奇点倍增器",
    "Sorta Automation": "排序自动化",
    "Start Producing Subatomic Particles": "开始生产亚原子粒子",
    "Start producing Universes": "开始制作宇宙",
    "Start the Universal Generation": "启动通用一代",
    "Stop producing Universes": "停止生产宇宙",
    "Subatomic Booster": "亚原子助推器",
    "THE END???": "结束？？？",
    "The Much more Universe Types": "更多的宇宙类型",
    "The very wanted upgrade": "非常想要的升级",
    "Triple Quantum Fluctuations": "三重量子涨落",
    "Universe generation no longer decreases Atoms": "宇宙生成不再减少原子",
    "x1e10 boost to the Other Universe Types": "x1e10 提升到其他宇宙类型",
    "x1e50 Replicanti Boost and unlocks a new tab": "x1e50 复制品 提升 并解锁新标签",
    "3x and Automatically generate Hevipelle points": "3x 并自动生成 复制品 点",
    "4th Omega Dimension": "欧米茄第四维度",
    "A boost everyone would like": "每个人都想要的提升",
    "A Gift from Antimatter Jesus": "来自反物质耶稣的礼物",
    "Atom Doubler": "原子倍增器",
    "Atom Self-Replication": "原子自我复制",
    "Autobuys Subatomic Dimensions and Subatomic Power Effect also boosts Subatomic Particles": "自动购买 亚原子尺寸和亚原子能量效应也提高了亚原子粒子",
    "Automates Infinity Point Doublers, Infinity Dimensions and Omega Dimensions.": "使无限点倍增器、无限维度和欧米茄维度自动化。",
    "Automates Singularity Doublers and Black Hole Doublers": "自动化奇点倍增器和黑洞倍增器",
    "Big Black Holes (AYO?": "大黑洞（AYO?",
    "Black Hole Doubler": "黑洞倍增器",
    "Boost Omega Dimensions based on Singularities": "基于奇点提升欧米茄维度",
    "Boost Replicanti Mult Gain based on 1st Infinity Dimension Mult": "基于 第 1 无限维度 乘数 提高 复制品 乘法增益",
    "Boosts Atoms based on Atoms": "基于 原子 提升 原子",
    "Boosts Electron effect pow to ^35": "将电子效应 力量 提升至 ^35",
    "Boosts Universes based on Atoms": "增强基于原子的宇宙",
    "Boosts Universes based on Time after buying this upgrade": "购买此升级后基于时间提升宇宙",
    "Boosts Universes based on Universes": "基于宇宙提升宇宙",
    "Cool Chemistry Stuff": "很酷的化学材料",
    "1st Infinity Dimension": "第 1 无限维度",
    "2nd Infinity Dimension": "第 2 无限维度",
    "3rd Infinity Dimension": "第 3 无限维度",
    "Automates buying Dimension Boosts, Galaxies, Production Multipliers, and Automatically gains Sacrifice mult, But unfortunately, stops autobuying buyables in the Incremental Layer and the Cookie Clicker layer. (This is due to performance issues it wont change anything gameplay-wise so dont worry": "自动购买 维度提升、星系、生产乘数，并自动获得 牺牲乘数，但不幸的是，在增量层和 不饼干点击器 层中停止自动购买可购买物品。 （这是由于性能问题，它不会改变任何游戏玩法，所以不用担心",
    "Finally, a lot of Money!": "最后，很多钱！",
    "Get Infinity Points": "获得无限点",
    "Gets 50% of Infinity Points production per Second": "每秒获得 50% 的 无限点 产量",
    "Infinite Synergy": "无限协同",
    "Infinity": "无限",
    "Infinity and Beyond!": "无限与超越！",
    "Infinity Points Doubler": "无限点倍增器",
    "Replicanti this early in the game?????": "复制人这么早？？？？",
    "The Boost of the Infinite Gods": "无限神的助推",
    "THE INFLATED UPGRADE #1": "膨胀升级#1",
    "Unlocks Infinity Dimensions": "解锁无限维度",
    "Why Not?": "为什么不？",
    "x10 Boost to all Infinity Dimensions and Infinity Points": "x10 提升到所有无限维度和无限点",
    "Boost to all Dimensions based on Infinity Points": "基于无限点提升到所有维度",
    "Boost to Infinity Points based on Infinity Points": "基于无限点提升到无限点",
    "Boost to the 1st Dimension based on Infinity Points": "基于无穷点提升到第 1 维度",
    "Reset your Replicanti for a Singularity": "重置您的 复制品 以获得奇点",
    "Singularity": "奇点",
    "A fighting Idle Game?": "格斗放置游戏？",
    "Abuses Timewalls, Trash, and a pile of GARBAGE!": "滥用时间墙、垃圾和一堆垃圾！",
    "Big Inflation So Funny": "大通货膨胀真有趣",
    "Boosts each other like brothers": "像兄弟一样互相鼓励",
    "Boosts Heroic points based on Heroic points": "根据英雄点数提升英雄点数",
    "Boosts Heroic points based on time after buying the Upgrade": "购买升级后根据时间提升英雄积分",
    "Boosts Player Max Health based on Military Power and Disables the Death Cooldown": "根据军事力量提高玩家最大生命值并禁用死亡冷却",
    "Development": "开发",
    "F**king Amount of Timewall.": "F**king 时间墙的数量。",
    "Finishes the Layer": "完成图层",
    "Finishes this Minigame and get 100% of Sell Value per Second": "完成此小游戏并获得每秒 100% 的 Sell Value",
    "Here lies the Timewalls of this game": "这就是这个游戏的时间墙",
    "i aint waiting 1 week for an upgrade": "我不会等待 1 周的升级",
    "I'm gonna be honest, the timewalls are the only things stopping this from being in my top mods": "老实说，时间墙是唯一能阻止它出现在我的顶级模组中的东西",
    "Icecreamdude's Games Discord Server": "Icecreamdude 的游戏 Discord 服务器",
    "id give u a 65 with the current timewalls": "id 给你一个 65 的当前时间墙",
    "Nobody liked you, you will never be missed.": "没有人喜欢你，你永远不会错过。",
    "Screw this lets just finish the game now": "搞砸了，让我们现在完成游戏",
    "Start becoming a Hero": "开始成为英雄",
    "THE END": "结束",
    "The Times": "时代",
    "This Minigame also has an End?": "这个小游戏也有结局？",
    "Timewall Graveyard": "时间墙墓地",
    "Unlocks a new tab :": "解锁新标签：",
    "Veteran Badge: Hardcaps Military Power Effect, but unlocks the upgrade for this layer's completion (Get 1e1000000 Military Power": "老兵徽章：硬顶军事力量效果，但解锁升级以完成这一层（获得 1e1000000 军事力量",
    "What about an Idle RPG game?": "闲置RPG游戏怎么样？",
    "You Gain Dollars Based on the Log10(Log10)^0.5 of Points you have": "您根据拥有的点数的 Log10(Log10)^0.5 获得美元",
    "You get 1 Heroic Point per Second": "你每秒获得 1 个英雄点数",
    "You know that nobody is gonna play that? There are already too many timewalls": "你知道没人会玩吗？时间墙已经太多了",
    "Boosts Damage based on Enemy Level": "根据敌人等级提升伤害",
    "Cid, the Helpful Adventurer": "Cid，乐于助人的冒险家",
    "Clicker Heroes": "点击英雄",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Python': 'Python',
    'Git游戏': 'Git游戏',
    'Javascript': 'Javascript',
    "Github": "Github",
    'IPhone': 'IPhone',
    'IPad': 'IPad',
    'PS5': 'PS5',
    'QQ群号': 'QQ群号',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "which multiplies incremental point gain by x": "它将增量点增益乘以 x",
    "Automation^": "自动化^",
    "Cookie Blood effect boosts Cultist, but exponentially drains Cookie Blood. Ritual Active: ": "饼干之血 效果会增强 邪教徒，但会以指数方式消耗 饼干之血。仪式活动：",
    "which multiplies Research Point and Cookie Time gain by x": "将研究点数和 饼干时间增益乘以 x",
    "which multiplies $ gain by ": "将 $ 收益乘以 ",
    "which multiplies Coin gain by ": "将 金币 收益乘以 ",
    "Gain Shards Per Second: ": "每秒获得碎片：",
    "Coins gained on Sell: ": "出售获得的金币：",
    "Current Respect Multiplier: ": "当前尊重乘数：",
    "Effect Shards Per Second: ": "每秒效果碎片：",
    "Speed up the Timewalls... Again": "加速时间墙……再一次",
    "Speed Up Timewalls by ": "加速时间墙 ",
    "Speeds up Timewall Seconds gain by ": "加速时间墙秒数增益 ",
    "Universes Per Second: ": "宇宙每秒：",
    "Boost all dimensions by x": "将所有维度提升 x",
    "Enemy HP: ": "敌人生命值：",
    "Damage Per Second: ": "伤害每秒：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    " Timewall Seconds": " 时间墙秒",
    " Second Cooldown For Death": " 秒死亡冷却时间",
    " Black Holes per second": " 黑洞每秒",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)e([\d\.,]+)\% \/ ([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^ee([\d\.]+)e([\d\.,]+)$/,
    /^xee([\d\.]+)e([\d\.,]+)$/,
    /^ee([\d\.]+)e([\d\.,]+)x$/,
    /^e([\d\.]+)e([\d\.,]+)x$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Deal (.+) Damage per Second$/, '每秒造成 $1 点伤害'],
    [/^Cost: (.+) Gold\n(.+)Level: (.+) \n(.+)boost to Damage Per Second$/, '成本：$1 黄金\n$2等级：$3 \n$4提升到伤害每秒'],
    [/^Requirement: (.+) 8th Dimensions\n(.+)Amount: (.+) Dimension Boosts\n(.+) multiplier to all Dimensions$/, '需要: $1 第 8 维度\n$2数量: $3 \n$4 维度提升\n $5 乘数 到 所有维度'],
    [/^Requirement: (.+) 8th Dimensions\n(.+)Amount: (.+) Antimatter Galaxies\n(.+) multiplier to dimension purchase$/, '需要: $1 第 8 维度\n$2数量: $3 \n$4 反物质星系\n $5 乘数 到 维度购买'],
    [/^Requirement: (.+) 8th Dimensions\n(.+)Amount: (.+) Antimatter Galaxies\n(.+) multiplier on dimension purchase$/, '需要: $1 第 8 维度\n$2数量: $3 \n$4 反物质星系\n $5 乘数 在 维度购买'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+) \n(.+) boost to Replicanti Time$/, '成本: $1 无限点\n$2数量: $3 \n$4 提升到 复制时间'],
    [/^Cost: (.+) Incremental Points\n(.+)Clicked: (.+) \n(.+) boost to 3rd, 4th, and 5th upgrades$/, '成本: $1 增量点\n$2点击数: $3 \n$4 提升到 第3、4、5 个升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Ideas: (.+) \n(.+) boost to Incremental Points$/, '成本: $1 增量点\n$2想法: $3 \n$4 提升到 增量点'],
    [/^Cost: (.+) Incremental Points\n(.+)Art Added: (.+) \n(.+) boost to incremental points$/, '成本: $1 增量点\n$2添加艺术: $3 \n$4 提升到 增量点'],
    [/^Cost: (.+) Incremental Points\n(.+)Layers: (.+) \n(.+) boost to points\nResets everything but Upgrades$/, '成本: $1 增量点\n$2层: $3 \n$4 提升到 点数\n重置所有东西，除了升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Different Industries: (.+) \n(.+) boost to the first (.+) buyables$/, '成本: $1 增量点\n$2不同产业: $3 \n$4 提升到 前 $5 可购买'],
    [/^Cost: (.+) Incremental Points\n(.+)Different Upgrades: (.+) \n(.+) boost to the fifth buyable$/, '成本: $1 增量点\n$2不同升级: $3 \n$4 提升到 第 5 可购买'],
    [/^Cost: (.+) Incremental Points\n(.+)Hours of Practice: (.+) \n(.+) boost to Points$/, '成本: $1 增量点\n$2练习时间: $3 \n$4 提升到 点数'],
    [/^Cost: (.+) Incremental Points\n(.+)Hours of Testing: (.+) \n(.+) boost to points$/, '成本: $1 增量点\n$2测试时间: $3 \n$4 提升到 点数'],
    [/^Cost: (.+) Incremental Points\n(.+)Lines of Code: (.+) \n(.+) boost to 3rd upgrade$/, '成本: $1 增量点\n$2代码行数: $3 \n$4 提升到 第3个 升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Lines of Code: (.+) \n(.+) boost to (.+)th upgrade$/, '成本: $1 增量点\n$2代码行数: $3 \n$4 提升到 第$5个 升级'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+) 1st Dimensions\n(.+) multiplier$/, '成本: $1 反物质\n$2数量: $3 第 1 维度\n$4 乘数'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Dimensional Grandmas$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 维度老奶奶'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to autowalking$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 自动行走'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Cookie Portal$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 饼干传送门'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Dimensional Cookies$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 维度饼干'],
    [/^Cost: (.+) Cultists\n(.+)Amount: (.+) \n(.+) Cookie Blood per second$/, '成本: $1 邪教徒\n$2数量: $3 \n$4 提升到 饼干之血每秒'],
    [/^Cost: (.+) Cookie Bibles\n(.+)Amount: (.+) \n(.+) boost to Cookie Bible income$/, '成本: $1 饼干圣经\n$2数量: $3 \n$4 提升到 饼干圣经收入'],
    [/^Cost: (.+) Wrinkler Juice\n(.+)Amount: (.+) \n(.+) boost to Wrinklers$/, '成本: $1 皱纹果汁\n$2数量: $3 \n$4 提升到 皱纹机'],
    [/^Cost: (.+) Wrinkler Juice\n(.+)Amount: (.+) \n(.+) boost to Cookie Antimatter Condensers$/, '成本: $1 皱纹果汁\n$2数量: $3 \n$4 提升到 饼干反物质冷凝器'],
    [/^Cost: (.+) Heavenly Chips\n(.+)Amount: (.+) \n(.+) boost to Cookie Antimatter Condensers$/, '成本: $1 天堂筹码\n$2数量: $3 \n$4 提升到 饼干反物质冷凝器'],
    [/^Cost: (.+) Heavenly Chips\n(.+)Amount: (.+) \n(.+) boost to Heavenly Chips$/, '成本: $1 天堂筹码\n$2数量: $3 \n$4 提升到 天堂筹码'],
    [/^Cost: (.+) Heavenly Chips\n(.+)Amount: (.+) \n(.+) boost to Cookie Prism$/, '成本: $1 天堂筹码\n$2数量: $3 \n$4 提升到 饼干棱镜'],
    [/^Cost: (.+) Points\n(.+)Amount: (.+) \n(.+) boost to all Dimensions$/, '成本: $1 点数\n$2数量: $3 \n$4 提升到 所有维度'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) Wrinkler Juice per Second$/, '成本: $1 糖块\n$2数量: $3 \n$4 皱纹果汁每秒'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Cookie Shipments$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 饼干出货量'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Sugar Lumps$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 糖块'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Cookie Prism$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 饼干棱镜'],
    [/^Cost: (.+) Sugar Lumps\n(.+)Amount: (.+) \n(.+) boost to Cookie Alchemy Labs$/, '成本: $1 糖块\n$2数量: $3 \n$4 提升到 饼干炼金术实验室'],
    [/^Cost: (.+) Respect\n(.+)Amount: (.+) \n(.+) Seconds in Training$/, '成本: $1 尊重\n$2数量: $3 \n$4 训练秒数'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookies$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Grandmas$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 老奶奶'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Farms$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干农场'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Banks$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干银行'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Portal$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干传送门'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Temples$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干神庙'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cursors$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 游标'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Mines$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干矿山'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Sugar Lumps$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 糖块'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Cookie Factories \nAlso produces Sugar Lumps$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 饼干工厂\n也生产糖块'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to Heavenly Chips$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到 天堂筹码'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) boost to X and Y Cookies$/, '成本: $1 饼干\n$2数量: $3 \n$4 提升到  X 和 Y 饼干'],
    [/^Cost: (.+) Cookies\n(.+)Amount: (.+) \n(.+) Heavenly Chips per second$/, '成本: $1 饼干\n$2数量: $3 \n$4 天堂筹码每秒'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+) 1st Dimensions\n(.+) multiplier$/, '成本: $1 反物质\n$2数量: $3 第 1 维度\n$4 乘数'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+) 2nd Dimensions\n(.+) multiplier$/, '成本: $1 反物质\n$2数量: $3 第 2 维度\n$4 乘数'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+) 3rd Dimensions\n(.+) multiplier$/, '成本: $1 反物质\n$2数量: $3 第 3 维度\n$4 乘数'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+)th Dimensions\n(.+) multiplier$/, '成本: $1 反物质\n$2数量: $3 5 维度\n$4 乘数'],
    [/^Cost: (.+) Antimatter\n(.+)Amount: (.+)th Dimensions\n(.+) multiplier to Replicanti$/, '成本: $1 反物质\n$2数量: $3 5 维度\n$4 乘数到复制品'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+) 1st Infinity Dimensions\n(.+) multiplier$/, '成本: $1 无限点\n$2数量: $3 第 1 无限维度\n$4 乘数'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+) 2nd Infinity Dimensions\n(.+) multiplier$/, '成本: $1 无限点\n$2数量: $3 第 2 无限维度\n$4 乘数'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+) 3rd Infinity Dimensions\n(.+) multiplier$/, '成本: $1 无限点\n$2数量: $3 第 3 无限维度\n$4 乘数'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+)th Infinity Dimensions\n(.+) multiplier$/, '成本: $1 无限点\n$2数量: $3 无限维度\n$4 乘数'],
    [/^Cost: (.+) Infinity Points\n(.+)Amount: (.+) Infinity Point Doublers\n(.+) multiplier to Infinity Points$/, '成本: $1 无限点\n$2数量: $3 无限点倍增器\n$4 乘数到无限点'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+) 1st Omega Dimensions\n(.+) multiplier$/, '成本: $1 黑洞\n$2数量: $3 第 1 欧米伽维度\n$4 乘数'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+) 2nd Omega Dimensions\n(.+) multiplier$/, '成本: $1 黑洞\n$2数量: $3 第 2 欧米伽维度\n$4 乘数'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+) 2nd Omega Dimensions\n(.+) multiplier to Replicanti$/, '成本: $1 黑洞\n$2数量: $3 欧米伽维度\n$4 乘数 到 复制品'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+) 3rd Omega Dimensions\n(.+) multiplier$/, '成本: $1 黑洞\n$2数量: $3 第 3 欧米伽维度\n$4 乘数'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+)th Omega Dimensions\n(.+) multiplier$/, '成本: $1 黑洞\n$2数量: $3 欧米伽维度\n$4 乘数'],
    [/^Cost: (.+) Black Holes\n(.+)Amount: (.+) Black Hole Doublers\n(.+) multiplier to Black Holes$/, '成本: $1 黑洞\n$2数量: $3 黑洞倍增器\n$4 乘数 到 黑洞'],
    [/^Cost: (.+) Electronic Dimensions\n(.+)Amount: (.+) 1st Subatomic Dimensions\n(.+) multiplier to Replicanti$/, '成本: $1 电子维度\n$2数量: $3 第 1 亚原子维度\n$4 乘数 到 复制品'],
    [/^Cost: (.+) Electronic Dimensions\n(.+)Amount: (.+) 1st Subatomic Dimensions\n(.+) multiplier$/, '成本: $1 电子维度\n$2数量: $3 第 1 亚原子维度\n$4 乘数'],
    [/^Cost: (.+) Electronic Dimensions\n(.+)Amount: (.+) 2nd Subatomic Dimensions\n(.+) multiplier$/, '成本: $1 电子维度\n$2数量: $3 第 2 亚原子维度\n$4 乘数'],
    [/^Cost: (.+) Electronic Dimensions\n(.+)Amount: (.+) 3rd Subatomic Dimensions\n(.+) multiplier$/, '成本: $1 电子维度\n$2数量: $3 第 3 亚原子维度\n$4 乘数'],
    [/^Cost: (.+) Atoms\n(.+)Amount: (.+) Replicanti Boosters\n(.+) multiplier to Replicanti$/, '成本: $1 原子\n$2数量: $3 复制品助推器\n$4 乘数到 复制品'],
    [/^Cost: (.+) Atoms\n(.+)Amount: (.+) Atom Doublers\n(.+) multiplier to Atoms$/, '成本: $1 原子\n$2数量: $3 原子倍增器\n$4 乘数到 原子'],
    [/^Cost: (.+) Singularities\n(.+)Amount: (.+) Singularity Doublers\n(.+) multiplier to Singularities$/, '成本: $1 奇点\n$2数量: $3 奇点倍增器\n$4 乘数到 奇点'],
    [/^Cost: (.+)\$\n(.+)Amount: (.+) \n(.+) Patreon Subscribers per Second$/, '成本: $1 \$\n$2数量: $3 \n$4 Patreon 订阅者每秒'],
    [/^You have written (.+) Lines of Code for autobuyer.js and a (.+) boost to game.js Lines of Code$/, '您为 autobuyer.js 编写了 $1 行代码，并为 game.js 提升了 $2 代码行'],
    [/^You Have (.+) in your Savings Account and a (.+) boost to Points$/, '您的储蓄账户中有 $1，点数获得 $2 提升'],
    [/^You have (.+) Cookie Bibles and a (.+) boost to all layer 1 buyables except the last one$/, '您有 $1 饼干圣经和 $2 提升到所有第 1 层可购买，除了最后一个'],
    [/^You have written (.+) Lines of Code for breakinfinity.js and a (.+) boost to autobuyer.js Lines of Code$/, '您已经为 breakinfinity.js 编写了 $1 行代码，并且对 autobuyer.js 代码行进行了 $2 提升'],
    [/^You have written (.+) Lines of Code for game.js and a (.+) boost to Hevipelle points$/, '您已经为 game.js 编写了 $1 行代码，并且对 hevipelle点 提升了 $2 '],
    [/^You have developed (.+) Timewalls a (.+) boost to all Antimatter Dimensions lines of code$/, '您已经开发了 $1 时间墙，对所有 反物质维度 代码行进行了 $2 提升'],
    [/^You have (.+) Cookie Blood and a (.+) boost to Cookie Bible production$/, '你有 $1 饼干之血 和 $2 的 饼干圣经 产量提升'],
    [/^You have (.+) Patreon Subscribers and a (.+) boost to \$ gain$/, '您有 $1 名 Patreon 订阅者和 $2 \$收益提升'],
    [/^You have (.+) Cultists and a (.+) boost to all layer all Dimensional cookies and Lumps$/, '你有 $1 个 邪教徒 和 $2 提升到所有层，所有维度饼干 和 糖块'],
    [/^You walked (.+) Meters Right$/, '你向右走了 $1 米'],
    [/^You walked (.+) Meters Forward$/, '你向前走了 $1 米'],
    [/^Your Salary is (.+) per hour$/, '你的薪水是每小时 $1'],
    [/^You Specifically Have (.+)$/, '你具体来说有 $1'],
    [/^Cookie Clicker Time: (.+) years (.+) boost to Points$/, '饼干点击器 时间：$1 年 $2 提升到点数'],
    [/^You have (.+) Antimatter and a (.+) boost to Cookie Time$/, '您有 $1 反物质和 $2 的 饼干时间提升'],
    [/^You have (.+) Items for Sale$/, '您有 $1 件待售物品'],
    [/^You have (.+) Hevipelle Shards and a (.+) boost to Other Universes Gain$/, '你有 $1 Hevipelle碎片 和 $2 提升到其它宇宙增益'],
    [/^You have (.+) Final Shards and a (.+) boost to Gain Shards and Effect Shards gain$/, '你有 $1 最终碎片和 $2 提升获得碎片和效果碎片增益'],
    [/^You have (.+) Gain Shards and a (.+) boost to Hevipelle shard Gain$/, '你有 $1 碎片增益和 $2 提升到 Hevipelle碎片增益'],
    [/^You have (.+) Effect Shards and a (.+) to the Hevipelle shard effect pow$/, '你有 $1 效果碎片和 $2 到 Hevipelle碎片效果力量'],
    [/^You have (.+) Infinity Power and a (.+) boost to all Dimensions$/, '你有 $1 无限能量和所有维度的 $2 提升'],
    [/^You are gaining (.+) Hevipelle Shards per Second$/, '你每秒获得 $1 Hevipelle 碎片'],
    [/^You are gaining (.+) Final Shards per Second, based on Points$/, '您每秒获得 $1 最终碎片，基于点数'],
    [/^You have (.+) Coins and a (.+) boost to Antimatter Dimensions Time$/, '你有 $1 硬币和 $2 反物质维度时间提升'],
    [/^Your \$ Converts to (.+) Euros in your Savings Account and a (.+) boost to Hevipelle Points$/, '您的 \$ 在您的储蓄账户中转换为 $1 欧元，并将 $2 提升为 Hevipelle 点数'],
    [/^Antimatter Dimensions Time: (.+) years (.+) boost to Cookie Clicker Time$/, '反物质维度时间：$1 年 $2 提升到 饼干点击器 时间'],
    [/^Enemy HP: (.+) Damage: (.+) Level: (.+)$/, '敌人生命值：$1 伤害：$2 等级：$3'],
    [/^Player HP: (.+) Damage: (.+)$/, '玩家生命值：$1 伤害：$2'],
    [/^You have (.+) Inspiration and a (.+) boost to Respect$/, '你有 $1 灵感和 $2 的尊重提升'],
    [/^You have (.+) Military Power and a (.+) boost to Respect$/, '你有 $1 军事力量和 $2 的尊重提升'],
    [/^You have (.+) Replicanti and a (.+) boost to all Infinity Dimensions$/, '你对所有无限维度都有 $1 复制品 和 $2 提升'],
    [/^You can go past (.+) Replicanti and get (.+) Singularities per Second$/, '你可以通过 $1 复制品 并获得每秒 $2 奇点'],
    [/^Produces 4th Mini Dimensions based on 8th Dimension Multiplier, and 1st Mini Dimensions boost 8th Dimensions\n(.+)1st Mini Dimensions: (.+)\n(.+)2nd Mini Dimensions: (.+)\n(.+)3rd Mini Dimensions: (.+)\n(.+)4th Mini Dimensions: (.+)\n(.+)1st Mini Dimension Effect: (.+) boost to 8th Dimensions$/, '根据第 8 维乘数产生第 4 迷你维度，第 1 迷你维度提升第 8 维度\n$1第 1 迷你维度：$2\n$3第 2 迷你维度：$4\n$5第 3 迷你维度：$6\n$7第 4 迷你维度： $8\n$9第一迷你维度效果：$10 提升到第八维度'],
    [/^You have (.+) Electronic Dimensions which Produced (.+) Electrons and a (.+) boost to Replicanti$/, '你有 $1 产生 $2 电子的电子维度和对 复制品 的 $3 提升'],
    [/^You have (.+) Omega Power and a (.+) boost to Black Holes$/, '你有 $1 欧米茄能量和 $2 提升到黑洞'],
    [/^You have (.+) Neutronic Dimensions which Produced (.+) Neutrons and a (.+) boost to Omega Dimensions$/, '你有 $1 中子维度，它产生了 $2 中子和一个 $2 提升到 欧米伽 维度'],
    [/^You are gaining (.+) Atoms per Second, based on Protons$/, '基于质子，您每秒获得 $1 原子'],
    [/^Produces Heviverses based on Hevipelle Points, and Multiverses boost Universe Upgrade Time gain\n(.+)Multiverses: (.+)\n(.+)Metaverses: (.+)\n(.+)Omniverses: (.+)\n(.+)Heviverses: (.+)\n(.+)Multiverse Effect: (.+) boost to Universe Upgrade Time$/, '根据 Hevipelle 点生成 Heviverses，多元宇宙 会增加 宇宙 升级时间增益\n$1多元宇宙：$2\n$3元宇宙：$4\n$5Omniverses：$6\n$7Heviverses：$\n$9多元宇宙 效果：$10 提升到宇宙升级时间'],
    [/^You have (.+) Black Holes and a (.+) boost to Infinity Points and Singularities$/, '你有 $1 黑洞和 $2 提升到无限点和奇点'],
    [/^You have (.+) Universes and a (.+) boost to Atoms$/, '你有 $1 宇宙 和对 原子 的 $2 提升'],
    [/^You have (.+) Atoms and a (.+) boost to all Subatomic Particle and Protonic, Neutronic, Electronic Dimension, and Replicanti Gain$/, '你有 $1 原子和 $2 提升到所有亚原子粒子和质子、中子、电子维度和 复制品 增益'],
    [/^You have (.+) Seconds to Replicate$/, '你有 $1 秒的复制时间'],
    [/^You have (.+) Subatomic Power and a (.+) boost to Protonic, Neutronic, and Electronic Dimensions.$/, '你有 $1 次原子能和 $2 提升到质子、中子和电子维度。'],
    [/^You lose all your dimensions before 8th dimension\n(.+) multiplier to 8th dimensions$/, '你失去了第 8 维度之前的所有维度\n $1 乘数到第 8 维度'],
    [/^You have (.+) Singularities and a (.+) boost to all Infinity Dimensions as well as a (.+) boost to all Mini Dimensions$/, '你有 $1 奇点和对所有无限维度的 $2 提升以及对所有迷你维度的 $3 提升'],
    [/^You have (.+) Cookies$/, '你有 $1 饼干'],
    [/^You have (.+) Protonic Dimensions which Produced (.+) Protons and a (.+) boost to Infinity Points$/, '你有 $1 质子维度，它产生了 $2 质子和 $3 提升到无限点'],
    [/^You have (.+) Infinity Points$/, '你有 $1 无限点'],
    [/^You have (.+) Research Points$/, '你有 $1 研究点'],
    [/^You have (.+) Heavenly Chips$/, '你有 $1 天堂筹码'],
    [/^You have (.+) Sugar Lumps$/, '你有 $1 糖块'],
    [/^You have (.+) Wrinkler Juice, which produces free Grandmas$/, '你有 $1 皱纹果汁，产生免费的 老奶奶'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)th Dimension$/, '第 $1 维度'],
	[/^(.+)th Mini Dimensions per Second$/, '第 $1 迷你维度 每秒'],
	[/^(.+)th Infinity Dimension$/, '第 $1 无限维度'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) \/ ([\d\.,]+) Seconds$/, '$1 \/ $2 秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOM(.+)\/sec$/, '$1 OOM$2\/秒'],
	[/^([\d\.,]+) OOM(.+)\/sec$/, '$1 OOM$2\/秒'],
	[/^([\d\.]+)e([\d\.,]+) OOM(.+)\/sec$/, '$1 OOM$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) per Second$/, '$1 每秒'],
    [/^([\d\.]+) incremental points$/, '$1 增量点'],
    [/^([\d\.]+) Infinity Poins on reset$/, '$1 无限点在重置时'],
    [/^([\d\.]+) Cookies$/, '$1 饼干'],
    [/^([\d\.]+)\$ per second$/, '$1\$ 每秒'],
    [/^([\d\.]+)e([\d\.,]+) Cookies$/, '$1e$2 饼干'],
    [/^([\d\.]+)e([\d\.,]+) hevipelle points$/, '$1e$2 hevipelle点'],
    [/^([\d\.]+)e([\d\.,]+) incremental points$/, '$1e$2 增量点'],
    [/^([\d\.]+)e([\d\.,]+) Heviverses per Second$/, '$1e$2 Heviverses 每秒'],
    [/^([\d\.]+)e([\d\.,]+) per Second$/, '$1e$2 每秒'],
    [/^ee([\d\.]+)e([\d\.,]+) Cookies$/, 'ee$1e$2 饼干'],
    [/^ee([\d\.]+)e([\d\.,]+) hevipelle points$/, 'ee$1e$2 hevipelle点'],
    [/^ee([\d\.]+)e([\d\.,]+) per Second$/, 'ee$1e$2 每秒'],
    [/^ee([\d\.]+)e([\d\.,]+) incremental points$/, 'ee$1e$2 增量点'],
    [/^ee([\d\.]+)e([\d\.,]+)\/sec$/, 'ee$1e$2\/秒'],
    [/^ee([\d\.]+)e([\d\.,]+)\$ per second$/, 'ee$1e$2\$ 每秒'],
    [/^([\d\.,]+) hevipelle points$/, '$1 hevipelle点'],
    [/^([\d\.,]+) per Second$/, '$1 每秒'],
    [/^([\d\.,]+)  Heroic Points$/, '$1 英雄点数'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\^(.+) boost to Point gain$/, '\*$1 提升到点数增益'],
    [/^x(.+) boost to Point gain, and unlock new stuff$/, 'x$1 提升到点数增益，并解锁新东西'],
    [/^Cost: (.+) Cultists$/, '成本：$1 邪教徒'],
    [/^Cost: (.+) Patreon Subscribers$/, '成本：$1 Patreon 订阅者'],
    [/^Cost: (.+) Research Points$/, '成本：$1 研究点'],
    [/^Cost: (.+) Heavenly Chips$/, '成本：$1 天堂筹码'],
    [/^Cost: (.+) Wrinkler Juice$/, '成本：$1 皱纹果汁'],
    [/^Cost: (.+) Cookie Bibles$/, '成本：$1 饼干圣经'],
    [/^Cost: (.+) Sugar Lumps$/, '成本：$1 糖块'],
    [/^Cost: (.+) Hevipelle Points$/, '成本：$1 hevipelle点数'],
    [/^Cost: (.+) hevipelle points$/, '成本：$1 hevipelle点数'],
    [/^Cost: (.+) incremental points$/, '成本：$1 增量点数'],
    [/^Cost: (.+) \$$/, '成本：$1 \$'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+)  Heroic Points$/, '成本：$1 英雄点数'],
    [/^Cost: (.+) Points$/, '成本：$1 点数'],
    [/^Cost: (.+) Cookies$/, '成本：$1 饼干'],
    [/^Cost: (.+)  Respect$/, '成本：$1 尊重'],
    [/^Cost: (.+) Gold$/, '成本：$1 黄金'],
    [/^Cost: (.+) Coins$/, '成本：$1 金币'],
    [/^Cost: (.+) Antimatter$/, '成本：$1 反物质'],
    [/^Cost: (.+) Infinity Points$/, '成本：$1 无限点'],
    [/^Cooldown: (.+) Seconds$/, '冷却：$1 秒'],
    [/^Item Value: (.+) Coins$/, '物品价值：$1 金币'],
    [/^Training Time Left: (.+) Seconds$/, '剩余训练时间：$1 秒'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);