/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Boost Point gain based on Incremental Points": "提升点数增益基于增量点",
    "Double your point gain.": "双倍你的点数增益。",
    "Incremental Game?": "增量游戏？",
    "incremental points": " 增量点",
    "It's a Great Idea": "这是个好主意",
    "The Beginning of the Idea": "想法的开始",
    "Triple your point gain.": "三倍你的点数增益。",
    "Boost Point gain based on Points": "提升点数增益基于点数",
    "Or Maybe Idle Game": "或者也许是放置游戏",
    "Boost Incremental Points based on Incremental Points": "提升增量点增益基于增量点",
    "I should start making the game?": "我应该开始制作游戏吗？",
    "Learn Coding": "学习编码",
    "Passively Generate Cookies": "被动生成饼干",
    "Start making the game": "开始制作游戏",
    "Upgrades": "升级",
    "You are gaining NaN incremental points per second": "您每秒获得 NaN 增量点",
    "Autobuys all the upgrades": "自动购买所有升级",
    "Autobuys the first 4 buyables and it does not deduct your Incremental Points": "自动购买前 4 个可购买，并且不会扣除您的增量点",
    "Automated Coding Lessons": "自动编码课程",
    "Clicker": "点击器",
    "Cookies": "饼干",
    "Free Points": "免费点数",
    "Gather Ideas": "收集想法",
    "Get 1e14 Incremental Points per second and autobuys the rest of the buyables": "每秒获得 1e14 增量点 并自动购买剩余的可购买",
    "Gain 100% of Incremental Points per second, and unlocks cool stuff": "每秒获得 100% 的增量点，并解锁很酷的东西",
    "Automates the second row of buyables": "自动化 第2行 可购买",
    "Boosts Incremental Points Based On Points": "提升增量点增益基于点数",
    "Make Developing Faster": "让开发更快",
    "Passive Income": "被动收入",
    "Pure Automation": "纯自动化",
    "Resets Sound Like a good idea!": "重置听起来是个好主意！",
    "Unlocks more cool stuff": "解锁更多酷的东西",
    "Prestige Function": "声望功能",
    "Time for rest can help right?": "休息时间可以帮助吗？",
    "Boost to Points and Incremental Points based on Time Played": "根据游戏时间提升点数和增量点",
    "Finish Coding": "完成编码",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Python': 'Python',
    'Git游戏': 'Git游戏',
    'Javascript': 'Javascript',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "which multiplies incremental point gain by x": "它将增量点增益乘以 x",
    "Automation^": "自动化^",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Cost: (.+) Incremental Points\n(.+)Clicked: (.+) \n(.+) boost to 3rd, 4th, and 5th upgrades$/, '成本: $1 增量点\n$2点击数: $3 \n$4 提升到 第3、4、5 个升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Ideas: (.+) \n(.+) boost to Incremental Points$/, '成本: $1 增量点\n$2想法: $3 \n$4 提升到 增量点'],
    [/^Cost: (.+) Incremental Points\n(.+)Layers: (.+) \n(.+) boost to points\nResets everything but Upgrades$/, '成本: $1 增量点\n$2层: $3 \n$4 提升到 点数\n重置所有东西，除了升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Different Industries: (.+) \n(.+) boost to the first (.+) buyables$/, '成本: $1 增量点\n$2不同产业: $3 \n$4 提升到 前 $5 可购买'],
    [/^Cost: (.+) Incremental Points\n(.+)Different Upgrades: (.+) \n(.+) boost to the fifth buyable$/, '成本: $1 增量点\n$2不同升级: $3 \n$4 提升到 第 5 可购买'],
    [/^Cost: (.+) Incremental Points\n(.+)Hours of Practice: (.+) \n(.+) boost to Points$/, '成本: $1 增量点\n$2练习时间: $3 \n$4 提升到 点数'],
    [/^Cost: (.+) Incremental Points\n(.+)Lines of Code: (.+) \n(.+) boost to 3rd upgrade$/, '成本: $1 增量点\n$2代码行数: $3 \n$4 提升到 第3个 升级'],
    [/^Cost: (.+) Incremental Points\n(.+)Lines of Code: (.+) \n(.+) boost to (.+)th upgrade$/, '成本: $1 增量点\n$2代码行数: $3 \n$4 提升到 第$5个 升级'],
    [/^You have (.+) Heavenly Chips$/, '你有 $1 天堂筹码'],
    [/^You have (.+) Sugar Lumps$/, '你有 $1 糖块'],
    [/^You have (.+) Wrinkler Juice, which produces free Grandmas$/, '你有 $1 皱纹果汁，产生免费的 老奶奶'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) incremental points$/, '$1 增量点'],
    [/^([\d\.]+) Cookies$/, '$1 饼干'],
    [/^([\d\.]+)e([\d\.,]+) Cookies$/, '$1e$2 饼干'],
    [/^([\d\.]+)e([\d\.,]+) incremental points$/, '$1e$2 增量点'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^\^(.+) boost to Point gain$/, '\*$1 提升到点数增益'],
    [/^x(.+) boost to Point gain, and unlock new stuff$/, 'x$1 提升到点数增益，并解锁新东西'],
    [/^Cost: (.+) incremental points$/, '成本：$1 增量点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Cookies$/, '成本：$1 饼干'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);